services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIRECT_URI=${REDIRECT_URI}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - HTTPS=${HTTPS}
      - SSL_CRT_FILE=${SSL_CRT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    command: ["npm", "start"]
    restart: always

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo.conf:/etc/mongo/mongo.conf:ro
    command: ["mongod", "--config", "/etc/mongo/mongo.conf"]
    restart: always

volumes:
  mongo-data:
