version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIRECT_URI=http://165.232.91.70:3000
      - CLIENT_ID=2b42a9bc4cdb42b4ad90f51353e95c31
      - CLIENT_SECRET=15a09064e44e402b87a135699dd1b245
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    command: ["npm", "start"]