services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIRECT_URI=http://localhost:3000
      - CLIENT_ID=2b42a9bc4cdb42b4ad90f51353e95c31
      - CLIENT_SECRET=15a09064e44e402b87a135699dd1b245
      - HTTPS=True
      - SSL_CRT_FILE=./ssl/cert.pem
      - SSL_KEY_FILE=./ssl/key.pem
      - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    command: ["npm", "start"]
